version: 2.1
orbs:
  circleci-cli: circleci/circleci-cli@0.1.8
jobs:
  build:
    docker:
      - image: circleci/node:10

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: yarn test

    

workflows:
  orb_tests:
    jobs:
    - build
    jobs:
      - cypress/install:
           build: "yarn install"
      - cypress/run: yarn test
